[package]
name = "text-splitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
either = "1.8.1"
itertools = "0.10.5"
once_cell = "1.17.1"
regex = "1.7.3"
thiserror = "1.0.40"
tokenizers = { version = "0.13.3", optional = true }
unicode-segmentation = "1.10.1"

[dev-dependencies]
fake = "2.5.0"
insta = { version = "1.29.0", features = ["yaml"] }

[features]
huggingface-tokenizers = ["dep:tokenizers"]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
