[package]
name = "text-splitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.8.1"
itertools = "0.10.5"
unicode-segmentation = "1.10.1"

[dev-dependencies]
fake = "2.5.0"
